on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.8.5' ]

    name: Maven ${{ matrix.maven }} sample

    steps:

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@1.3.1
        with:
          java-version: 11
          maven-version: ${{ matrix.maven }}
      - run: mvn -V